package com.main.todonotes.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF4800B2)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF6200EE)
val md_theme_light_onPrimaryContainer = Color(0xFFD0BEFF)
val md_theme_light_secondary = Color(0xFF006A60)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFF4AF8E3)
val md_theme_light_onSecondaryContainer = Color(0xFF006F64)
val md_theme_light_tertiary = Color(0xFF3B0DB6)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF5335CD)
val md_theme_light_onTertiaryContainer = Color(0xFFCBC1FF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFF9F9FE)
val md_theme_light_onBackground = Color(0xFF1A1C1F)
val md_theme_light_surface = Color(0xFFF9F9FE)
val md_theme_light_onSurface = Color(0xFF1A1C1F)
val md_theme_light_surfaceVariant = Color(0xFFE2E2E7)
val md_theme_light_onSurfaceVariant = Color(0xFF494456)
val md_theme_light_outline = Color(0xFF7A7488)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F5)
val md_theme_light_inverseSurface = Color(0xFF2E3034)
val md_theme_light_inversePrimary = Color(0xFFCFBDFF)
val md_theme_light_surfaceTint = Color(0xFF6D23F9)
val md_theme_light_outlineVariant = Color(0xFFCBC3D9)
val md_theme_light_scrim = Color(0xFF000000)